basePath: /
definitions:
  models.CreateUserInput:
    properties:
      email:
        example: efren@example.com
        type: string
      full_name:
        example: Efren David
        type: string
      password:
        example: miPasswordSeguro123
        type: string
    required:
    - email
    - full_name
    - password
    type: object
  models.GeminiProcessingFileIDResponse:
    properties:
      task_id:
        example: 8b9a1d2e-3c4f-5a6b-7c8d-9e0f1a2b3c4d
        type: string
    type: object
  models.GeminiProcessingFileResponse:
    properties:
      error:
        type: string
      id:
        example: 8b9a1d2e-3c4f-5a6b-7c8d-9e0f1a2b3c4d
        type: string
      result:
        example: Sí, existen varias becas...
        type: string
      status:
        allOf:
        - $ref: '#/definitions/models.GeminiProcessingStatus'
        example: finalizado
    type: object
  models.GeminiProcessingIDResponse:
    properties:
      task_id:
        example: 8b9a1d2e-3c4f-5a6b-7c8d-9e0f1a2b3c4d
        type: string
    type: object
  models.GeminiProcessingResponse:
    properties:
      error:
        type: string
      id:
        example: 8b9a1d2e-3c4f-5a6b-7c8d-9e0f1a2b3c4d
        type: string
      result:
        example: Sí, existen varias becas...
        type: string
      status:
        allOf:
        - $ref: '#/definitions/models.GeminiProcessingStatus'
        example: finalizado
    type: object
  models.GeminiProcessingStatus:
    enum:
    - pendiente
    - en_proceso
    - finalizado
    - error
    type: string
    x-enum-varnames:
    - StatusPending
    - StatusProcessing
    - StatusCompleted
    - StatusError
  models.PromptRequest:
    properties:
      prompt:
        example: Conoces las becas para poder estudiar en finlandia o noruega?
        type: string
    type: object
  models.User:
    properties:
      email:
        example: efren@example.com
        type: string
      full_name:
        example: Efren David
        type: string
      id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API RESTful para gestión de usuarios
  title: API GEMINI
  version: "1.0"
paths:
  /gemini/process:
    post:
      consumes:
      - application/json
      description: Inicia una tarea en segundo plano para procesar un prompt con la
        API de Gemini.
      parameters:
      - description: Prompt a procesar
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/models.PromptRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Solicitud aceptada y procesando
          schema:
            $ref: '#/definitions/models.GeminiProcessingIDResponse'
        "400":
          description: JSON de solicitud inválido
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - gemini
  /gemini/process/file:
    post:
      consumes:
      - multipart/form-data
      description: Procesa un prompt y un archivo de forma asíncrona, guarda los datos
        y retorna un ID de proceso.
      parameters:
      - description: Texto del prompt
        in: formData
        name: prompt
        required: true
        type: string
      - description: Archivo (PDF, PNG, JPEG)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Proceso en cola
          schema:
            $ref: '#/definitions/models.GeminiProcessingFileIDResponse'
        "400":
          description: Solicitud inválida
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - gemini
  /gemini/status-file/{gemini_processing_id}:
    get:
      consumes:
      - application/json
      description: Consulta el estado y el resultado de una tarea por su ID.
      parameters:
      - description: ID del proceso
        in: path
        name: gemini_processing_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Estado del proceso y resultado
          schema:
            $ref: '#/definitions/models.GeminiProcessingFileResponse'
        "400":
          description: ID de proceso inválido
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - gemini
  /gemini/status/{gemini_processing_id}:
    get:
      consumes:
      - application/json
      description: Consulta el estado y el resultado de una tarea por su ID.
      parameters:
      - description: ID del proceso
        in: path
        name: gemini_processing_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Estado del proceso y resultado
          schema:
            $ref: '#/definitions/models.GeminiProcessingResponse'
        "400":
          description: ID de proceso inválido
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - gemini
  /users:
    post:
      consumes:
      - application/json
      description: Crea un usuario nuevo con contraseña
      parameters:
      - description: Datos para crear usuario
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear un usuario
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Devuelve la información de un usuario por su ID
      parameters:
      - description: ID del usuario
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener un usuario por ID
      tags:
      - users
swagger: "2.0"
